name: tasklog_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  build_runner: ^2.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Jost-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Jost-Black.ttf
          weight: 900
        - asset: assets/fonts/Jost-BlackItalic.ttf
          weight: 900
          style: italic


